#! /bin/python3

import pwn
import subprocess
import re
import os
from time import sleep

path = "/path/to/your/keepass.kdbx"
a = pwn.process(['keepassxc-cli', 'open', path])
a.recvuntil(":")


cmd = ['dmenu', '-fn', 'Hack', '-nb', '#000000', '-sb', '#d79921', '-sf',
       '#1d2021', '-nf', '#000000', '-p', 'Type in keepass passphrase']
proc = subprocess.Popen(cmd, universal_newlines=True, stdin=subprocess.PIPE,
                        stdout=subprocess.PIPE, stderr=subprocess.PIPE)
with proc.stdin:
    proc.stdin.write('')
if proc.wait() == 0:
    mdp = proc.stdout.read().rstrip('\n')
else:
    exit(1)


a.sendline(mdp)
rep = a.recvuntil(b"> ").decode()
print(rep)
if re.search("\n\x1b\[6 q.+> ", rep) is None:
    os.system('notify-send "KeepassXC" "Wrong passphrase"')
    exit(1)

a.sendline("ls -Rf")
liste = a.recvuntil(b"> ").decode().split("\n")[1:-1]

for i in liste:
    if i[-1] == '/':
        liste.remove(i)

cmd = ['dmenu', '-fn', 'Hack', '-nb', '#000000', '-l', '5' '-i',
       '-p', 'Type in password']
proc = subprocess.Popen(cmd, universal_newlines=True, stdin=subprocess.PIPE,
                        stdout=subprocess.PIPE, stderr=subprocess.PIPE)
with proc.stdin:
    for i in liste:
        proc.stdin.write(i)
        proc.stdin.write('\n')
if proc.wait() == 0:
    pwd = proc.stdout.read().rstrip('\n')
else:
    exit(1)

if pwd not in liste:
    os.system('notify-send "KeepassXC" "Your password doesn\'t exist"')
    exit(1)

a.sendline('clip "{}"'.format(pwd))
a.recvuntil("> ").decode()
sleep(10)
a.close()
